IMPORTING LIBRARIES FOR THE MODEL PREDICTION

In [24]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import pickle

IMPORTING DATASET

In [25]:
df = pd.read_csv(r'G:\machine learning\Datasets\forestfire\forestfire.csv')
df

Area  Oxygen  Temperature  Humidity  Fire Occurrence
0    Jharkand      40           45        20                1
1   Bangalore      50           30        10                1
2     Ecuador      10           20        70                0
3           a      60           45        70                1
4   Bangalore      30           48        10                1
5           c      50           15        30                0
6          de       5           35        35                0
7         asd       5           20        70                0
8     Ecuador      60           32        19                1
9           r      30           50        45                1
10          t      40           55        80                1
11          y      30           39       100                0
12   Jharkand      10           12        12                0
13  Bangalore      20           23        23                0
14    Ecuador      60           34        15                1
15     canada      80            4        68                0
16          c      25           56        79                1
17          c      12           45        90                0
18        asd      28           43        15                1
19        asd      26            0        32                0
20         ad      32           37        21                1
21       sasd      45           48        12                1
22        asd      56           15        65                0
23      asdas      67           45        33                1
24        das      78           49         8                1
25        das      89           45        18                1
26        ads      21           12        44                0
27        ads      11           20        59                0
28        asd       1           32        70                0
29        NaN       5           20        45                0
30        NaN      42           43        20                1
31        NaN      32           60        30                1
32        NaN       5           15         5                0
33        NaN      20           30         5                0
34        NaN      30           51         2                1
35        NaN      60           60        10                1
36        NaN      10           10        60                0
37        NaN       0           30         0                0
38        NaN      45           45        15                1

In [26]:
df = np.array(df)

In [27]:
X = df[:,1:-1]
y = df[:,-1]

In [28]:
y = y.astype('int')

In [29]:
X = X.astype('int')

In [30]:
X

array([[ 40,  45,  20],
       [ 50,  30,  10],
       [ 10,  20,  70],
       [ 60,  45,  70],
       [ 30,  48,  10],
       [ 50,  15,  30],
       [  5,  35,  35],
       [  5,  20,  70],
       [ 60,  32,  19],
       [ 30,  50,  45],
       [ 40,  55,  80],
       [ 30,  39, 100],
       [ 10,  12,  12],
       [ 20,  23,  23],
       [ 60,  34,  15],
       [ 80,   4,  68],
       [ 25,  56,  79],
       [ 12,  45,  90],
       [ 28,  43,  15],
       [ 26,   0,  32],
       [ 32,  37,  21],
       [ 45,  48,  12],
       [ 56,  15,  65],
       [ 67,  45,  33],
       [ 78,  49,   8],
       [ 89,  45,  18],
       [ 21,  12,  44],
       [ 11,  20,  59],
       [  1,  32,  70],
       [  5,  20,  45],
       [ 42,  43,  20],
       [ 32,  60,  30],
       [  5,  15,   5],
       [ 20,  30,   5],
       [ 30,  51,   2],
       [ 60,  60,  10],
       [ 10,  10,  60],
       [  0,  30,   0],
       [ 45,  45,  15]])

In [31]:
y = y.reshape(len(y),1)

In [32]:
y

array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1]])

SPLITING DATASET INTO TRAINING SET AND TESTING SET

In [33]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state=0)

PREDICTING WITH LOGISTIC REGRESSION MODEL

In [34]:
log_reg = LogisticRegression()


In [35]:
log_reg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
prediction = log_reg.predict(X_test)
prediction

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0])

In [37]:
prediction = log_reg.predict([[45,32,60]])
prediction

array([0])

PREDICTING WITH SUPPORT VECTOR CLASSIFIER MODEL

In [38]:
svm_classifier = SVC()
svm_classifier.fit(X_train,y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [41]:
prediction = svm_classifier.predict(X_test)

In [42]:
prediction

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0])

In [45]:
svm_classifier.score(X_test,y_test)

0.9166666666666666

In [46]:
log_reg.score(X_test,y_test)

1.0

In [48]:
pickle.dump(log_reg,open('forestfiremodel.pickle','wb'))
model = pickle.load(open('forestfiremodel.pickle','rb'))

In [ ]:
model